spring:
  application:
    name: F1 calendar

  h2:
    console:
      enabled: true

  datasource: # configuration H2 database
    url: jdbc:h2:mem:testDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  dependencies:
    api:
      openf1:
        base-url: "https://api.openf1.org"
        meeting-endpoint: "/v1/meetings"