name: Full CI/CD Pipeline

on:
  pull_request:
    branches: [ development, main ]
  push:
    branches: [ main ]

jobs:
  check-version:
    uses: ./.github/workflows/01-check-version.yml
    permissions:
      contents: read
      packages: read

  build-and-test:
    needs: check-version
    uses: ./.github/workflows/02-build-test.yml

  security-analysis:
    needs: build-and-test
    uses: ./.github/workflows/03-security.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-push:
    needs: security-analysis
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/04-docker.yml
    permissions:
      contents: read
      packages: write

#TODO:
#  deploy-local-k8s:
#    needs: docker-push
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    uses: ./.github/workflows/05-deploy.yml
#    secrets: inherit